# Generated by Django 6.0.3 on 2026-04-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendancerecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegelocation',
            name='name',
            field=models.CharField(default='College Campus', max_length=100),
        ),
    ]
