# Generated by Django 6.0.3 on 2026-04-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_collegelocation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='total_students',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
