# Generated by Django 6.0.3 on 2026-04-12 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_otpreset_registrationrequest_is_google_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegelocation',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegelocation',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegelocation',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.subject'),
        ),
    ]
