# Generated by Django 6.0.3 on 2026-04-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_collegelocation_end_time_collegelocation_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegelocation',
            name='days_of_week',
            field=models.CharField(default='0,1,2,3,4,5', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
