# Generated by Django 6.0.3 on 2026-04-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_collegelocation_days_of_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='device_id',
        ),
    ]
