# Generated by Django 6.0.3 on 2026-04-16 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_alter_attendancerecord_status_delete_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='end_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holiday',
            name='start_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
