# Generated by Django 6.0.3 on 2026-04-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_fix_model_bugs_phone_holiday_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='attendance.branch'),
        ),
        migrations.AddField(
            model_name='subject',
            name='domains',
            field=models.ManyToManyField(blank=True, to='attendance.domain'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semesters',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='attendance.semester'),
        ),
    ]
