# Generated by Django 6.0.3 on 2026-04-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_subject_branches_subject_domains_subject_semesters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
    ]
