# Generated by Django 6.0.3 on 2026-04-16 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_remove_subject_branch_remove_subject_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='domains',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semesters',
        ),
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.branch'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.semester'),
        ),
    ]
