# Generated by Django 6.0.3 on 2026-04-20 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegelocation',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.subject'),
        ),
    ]
